Use inotifywait to monitor file changes

diff --git a/ruby-rspec/ruby_app/bin/start_tests b/ruby-rspec/ruby_app/bin/start_tests
--- a/ruby-rspec/ruby_app/bin/start_tests
+++ b/ruby-rspec/ruby_app/bin/start_tests
@@ -1,5 +1,19 @@
 #!/bin/bash
 
-set -e
+while true; do
+  bundle exec rspec
+  # tests_passed=$?
 
-fswatch -0or . | xargs -0 bundle exec rspec
+  # if $tests_passed; then
+  #   git add .
+  #   git commit -m "Passing specs"
+  # else
+  #   if [ "$SPECHERO_ROLE" != "hero" ]; then
+  #     git add .
+  #     git commit -m "Failing specs"
+  #   fi
+  # fi
+
+  # Wait for the next file to change
+  inotifywait -rq . || break
+done
